version: "3.8"

services:
  next:
    build:
      context: ./apps/next
      dockerfile: ./Dockerfile
    env_file:
      - "./apps/next/.env"
    ports:
      - "3030:3030"
    volumes:
      - ./apps/next/public:/web/public
    restart: unless-stopped
    networks:
      - web-handson-network

networks:
  web-handson-network:
    driver: bridge